"""empty message

Revision ID: 3ad5c81f9af2
Revises: 
Create Date: 2020-08-20 14:26:04.181056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad5c81f9af2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('artist', sa.String(length=100), nullable=False))
    op.add_column('songs', sa.Column('description', sa.String(length=400), nullable=False))
    op.create_unique_constraint(None, 'songs', ['description'])
    op.create_unique_constraint(None, 'songs', ['artist'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='unique')
    op.drop_constraint(None, 'songs', type_='unique')
    op.drop_column('songs', 'description')
    op.drop_column('songs', 'artist')
    # ### end Alembic commands ###
