"""empty message

Revision ID: 3b4b354c490c
Revises: 
Create Date: 2020-08-13 14:48:26.688689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4b354c490c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('songID', sa.Integer(), nullable=False),
    sa.Column('songName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('songID'),
    sa.UniqueConstraint('songName')
    )
    op.create_table('songs_on_box',
    sa.Column('songID', sa.Integer(), nullable=True),
    sa.Column('boxID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boxID'], ['boxes.boxID'], ),
    sa.ForeignKeyConstraint(['songID'], ['songs.songID'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs_on_box')
    op.drop_table('songs')
    # ### end Alembic commands ###
