"""empty message

Revision ID: 7394cb6452bd
Revises: bfe7c42b6583
Create Date: 2020-08-17 00:58:35.730476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7394cb6452bd'
down_revision = 'bfe7c42b6583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_email', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('user_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('user_password', sa.String(length=100), nullable=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['user_email'])
    op.drop_column('users', 'name')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'user_password')
    op.drop_column('users', 'user_name')
    op.drop_column('users', 'user_email')
    # ### end Alembic commands ###
