"""empty message

Revision ID: 89ed6714130c
Revises: 
Create Date: 2020-08-23 14:37:12.823874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ed6714130c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'description',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
    op.drop_constraint('songs_description_key', 'songs', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('songs_description_key', 'songs', ['description'])
    op.alter_column('songs', 'description',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
    # ### end Alembic commands ###
